# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3700be7cde0fe5d5aa4fa946131530c36b75b0ded75eb0f5f794941b196b201fc2ab0d0ef451abbbfb29f2e32c509e4cad768623b9c0db45b77ba33fe42fc85c

test:
  secret_key_base: 1bd5a540fef248f14adac45b0be7f9104f32eaa659a58e065450f1da2818ab2c3198f6aee576a7ce340d9337dd9d761f5b8ecc8ad0a3a98bc38cea4916d6b35b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
